#define SCRIPT_PARSER_TK_GDB                             1
#define SCRIPT_PARSER_TK_STRING                          2
#define SCRIPT_PARSER_TK_INTO                            3
#define SCRIPT_PARSER_TK_OPEN                            4
#define SCRIPT_PARSER_TK_CREATE                          5
#define SCRIPT_PARSER_TK_NODE                            6
#define SCRIPT_PARSER_TK_PAREN_OPEN                      7
#define SCRIPT_PARSER_TK_PAREN_CLOSE                     8
#define SCRIPT_PARSER_TK_COMMA                           9
#define SCRIPT_PARSER_TK_BOOLEAN                        10
#define SCRIPT_PARSER_TK_INTEGER                        11
#define SCRIPT_PARSER_TK_LONG                           12
#define SCRIPT_PARSER_TK_DOUBLE                         13
#define SCRIPT_PARSER_TK_OID                            14
#define SCRIPT_PARSER_TK_TIMESTAMP                      15
#define SCRIPT_PARSER_TK_TEXT                           16
#define SCRIPT_PARSER_TK_BASIC                          17
#define SCRIPT_PARSER_TK_INDEXED                        18
#define SCRIPT_PARSER_TK_UNIQUE                         19
#define SCRIPT_PARSER_TK_TO                             20
#define SCRIPT_PARSER_TK_MATERIALIZE                    21
#define SCRIPT_PARSER_TK_NEIGHBORS                      22
#define SCRIPT_PARSER_TK_EDGE                           23
#define SCRIPT_PARSER_TK_FROM                           24
#define SCRIPT_PARSER_TK_DIRECTED                       25
#define SCRIPT_PARSER_TK_UNDIRECTED                     26
#define SCRIPT_PARSER_TK_DROP                           27
#define SCRIPT_PARSER_TK_ATTRIBUTE                      28
#define SCRIPT_PARSER_TK_DOT                            29
#define SCRIPT_PARSER_TK_INDEX                          30
#define SCRIPT_PARSER_TK_LOAD                           31
#define SCRIPT_PARSER_TK_COLUMNS                        32
#define SCRIPT_PARSER_TK_NODES                          33
#define SCRIPT_PARSER_TK_EDGES                          34
#define SCRIPT_PARSER_TK_LOCALE                         35
#define SCRIPT_PARSER_TK_ASTERISK                       36
#define SCRIPT_PARSER_TK_IGNORE                         37
#define SCRIPT_PARSER_TK_WHERE                          38
#define SCRIPT_PARSER_TK_TAIL                           39
#define SCRIPT_PARSER_TK_EQUAL                          40
#define SCRIPT_PARSER_TK_HEAD                           41
#define SCRIPT_PARSER_TK_FIELDS                         42
#define SCRIPT_PARSER_TK_TERMINATED                     43
#define SCRIPT_PARSER_TK_ENCLOSED                       44
#define SCRIPT_PARSER_TK_ALLOW                          45
#define SCRIPT_PARSER_TK_MULTILINE                      46
#define SCRIPT_PARSER_TK_NUMBER                         47
#define SCRIPT_PARSER_TK_MAX                            48
#define SCRIPT_PARSER_TK_MODE                           49
#define SCRIPT_PARSER_TK_ROWS                           50
#define SCRIPT_PARSER_TK_SPLIT                          51
#define SCRIPT_PARSER_TK_PARTITIONS                     52
#define SCRIPT_PARSER_TK_SET                            53
#define SCRIPT_PARSER_TK_FORMAT                         54
